### ISSUE TITLE
Do you want to paricipate to steadfast3?

### ISSUE THREAD

**Issue by MFDGaming** [Steadfast5/Steadfast5#2]
Please leave some credits to me ialdrich23xX and pocketminesmash because we spent a lot of time fixing stuff and adding stuff

**Comment by MFDGaming** [comment]
@IceCruelStuff

**Comment by MFDGaming** [comment]
@IceCruelStuff thanks

**Comment by MFDGaming** [comment]
For the credits

**Comment by MFDGaming** [comment]
Do you have discord?

**Comment by IceCruelStuff** [comment]
yes

**Comment by MFDGaming** [comment]
@IceCruelStuff can you add me I am MFD#6902

**Comment by IceCruelStuff** [comment]
ok
