### ISSUE TITLE
can't join server

### ISSUE THREAD

**Issue by junxiesky** [Steadfast5/Steadfast5#77]
I use 1.14.60.5 client And 1.8.3 of server software 
Unable to enter

**Comment by junxiesky** [comment]
ummm
When can this problem be solved?

**Comment by IceCruelStuff** [comment]
Right now I'm testing to see if 1.14.60 works. It will come out very soon.

**Comment by IceCruelStuff** [comment]
@junxiesky Does it give you an error or are you just unable to join the server?

**Comment by junxiesky** [comment]
> @junxiesky它是否给您一个错误，或者您只是无法加入服务器？

Just can't join the server

**Comment by MFDGaming** [comment]
try out http://github.com/MFDGaming/PocketMine-SteadFast3 and youll be able to connect
